services:
  # 3 Servers for load balancing
  server1:
    hostname: server1
    restart: unless-stopped
    build:
      context: ./server
    container_name: server1
  server2:
    hostname: server2
    restart: unless-stopped
    build:
      context: ./server
    container_name: server2
  server3:
    hostname: server3
    restart: unless-stopped
    build:
      context: ./server
    container_name: server3

  client:
    build:
      context: ./client
    container_name: client

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - server1
      - server2
      - server3
